compile:
	javac -cp .:/home/clement/JCSP/jcsp-1.1-rc4/jcsp.jar:/home/clement/JCSP/jcsp-1.1-rc4/jcsp-demos-util.jar *.java
run:
	java -cp .:/home/clement/JCSP/jcsp-1.1-rc4/jcsp.jar:/home/clement/JCSP/jcsp-1.1-rc4/jcsp-demos-util.jar FireworksMain  
